version: "3.9"

services:
  web_app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - static_v:/app/static
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static_v:/static/
    depends_on:
      - web_app

  db:
    image: postgres:13
    env_file:
      - .postgres.env
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
  static_v: