# Generated by Django 4.1.3 on 2022-11-12 22:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(db_index=True, max_length=50)),
                ("balance", models.PositiveBigIntegerField(default=0)),
                ("capacity", models.PositiveIntegerField()),
                ("expire_at", models.DateTimeField()),
            ],
            options={
                "db_table": "coupons",
                "ordering": ("expire_at",),
            },
        ),
    ]
