# Generated by Django 4.1.3 on 2022-11-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0002_coupon_used_by_couponusage"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
