# Generated by Django 4.1.3 on 2022-11-13 07:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("coupons", "0003_coupon_is_active"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="couponusage",
            unique_together={("coupon", "account")},
        ),
    ]
